version: 2
updates:
  # Uncomment and configure for your package ecosystem:
  #
  # - package-ecosystem: npm
  #   directory: /
  #   schedule:
  #     interval: weekly
  #
  # - package-ecosystem: pip
  #   directory: /
  #   schedule:
  #     interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
